### ISSUE TITLE
Use substring matching for external link images

### ISSUE THREAD

**Issue by infotexture** [alvaromontoro/almond.css#10]
The [current selectors for external links](https://github.com/alvaromontoro/almond.css/blob/master/src/general/extension.images.scss#L35) assume the `external` keyword is the **only** value for the `rel` attribute, but this syntax misses any links where the `rel` attribute also contains other [link types](https://html.spec.whatwg.org/multipage/links.html#linkTypes) keywords, such as `noopener`, so an external link like this wouldn't get the icon prefix:

```html
<a href="http://www.example.com" target="_blank" rel="external noopener">some site</a>
```

Adding a tilde to the corresponding selectors would ensure that the rules match even when other keywords are present:

```diff 
- a[rel="external"] {
+ a[rel~="external"] {
```

> An `<a>` element with an attribute `rel` whose value is a space-separated list of values, one of which is `external`.

Noticed this with external links, but might also apply to bookmark links.

**Comment by alvaromontoro** [comment]
This is a good catch. I will work on it unless you want to create a PR yourself (it seems you already know the solution)

**Comment by infotexture** [comment]
I went ahead and submitted #11 to implement these changes and fixed a few minor details in the README while I was at it.

Each change is in a separate commit, so feel free to accept/reject or cherry-pick as you see fit.

Thanks for building this. 🙏
