### ISSUE TITLE
Licensing inquiry

### ISSUE THREAD

**Issue by infotexture** [alvaromontoro/almond.css#13]
Hi Álvaro,

I’ve been experimenting with Almond.CSS again lately for the static HTML docs of an [open-source project](https://www.dita-ot.org) I work on.

I just noticed Almond’s GPL license and realized this would prevent us from using it, since our project is Apache-licensed. 

_(If I understand correctly, GPL requires any derivative work to also be under the GPL, but this is not an option for us because while our project itself is free and open source, it is sometimes used in commercial software, so we cannot switch to GPL.)_

Would you consider releasing Almond.CSS under a more permissive license such as the [Apache License 2.0](https://choosealicense.com/licenses/apache-2.0/) or [MIT License](https://choosealicense.com/licenses/mit/) that would allow it to be used in projects like ours?

If you made a conscious choice for GPL3 on principle, I understand entirely. 

— Just wanted to ask and take the opportunity to thank you again for building this. 🙏

**Comment by alvaromontoro** [comment]
Hi Roger! Let me check the licensing and how it works. I thought that with this license you could use it in any project independently of their license, and it was the library itself that you needed to release with the same license as the original if you made changes.

I'm ok with you using Almond.CSS for any type of project (as long as it's legal :P) If it's ok just with written permission from the author, take this comment as such.

**Comment by alvaromontoro** [comment]
Changed license to MIT
