### ISSUE TITLE
Add build instructions to ReadMe

### ISSUE THREAD

**Issue by infotexture** [alvaromontoro/almond.css#4]
For people who are interested in adapting this to their own needs, it would be helpful to include build instructions in the ReadMe.

Many devs will be able to figure it out just by reading `package.json`, but others might benefit from a few extra pointers on how to re-generate the distribution CSS after changing any of the Sass source files.

Might also be nice to add a `watch` script that will automatically re-generate the CSS whenever Sass files change. 🤔

**Comment by alvaromontoro** [comment]
I added a `watch` script, but it only generates the unminified version. Also updated the documentation with instructions on how to build and run locally (let me know if they look ok).

Thanks for the suggestions! It is a nice improvement :)

**Comment by infotexture** [comment]
🎉 Brilliant, thanks for implementing this. 🙏 

Should make it much easier for others to build something of their own with AlMonD. 👍
