### ISSUE TITLE
<input type="text"> sizes don't work

### ISSUE THREAD

**Issue by fabi321** [alvaromontoro/almond.css#43]
**Describe the bug**
If I specify a size for an text input, it is being ignored and the text field stays at the same width.

**Steps to reproduce**
1. Use `<input type="text" size="5">` next to `<input type="text" size="20">` with and without the stylesheet.
2. While the sizes are different without a stylesheet (tested in Firefox, [according to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text#size) it's a common feature) they stay the same with Almond.css enabled

**Expected behavior**
The width should be different, depending on the given size.

**Screenshots**

Input fields without Almond.
![Input without Almond](https://user-images.githubusercontent.com/42294590/155983573-db01232b-ec35-452e-93a2-ba1d192edb02.PNG)
Input fields with Almond.
![Input with Almond](https://user-images.githubusercontent.com/42294590/155983612-c1370309-5fc2-4278-b598-7fa8024ded2b.PNG)

**Devices**
Desktop:
 - OS: Windows
 - Browser: Firefox
 - Version: 97

**Comment by alvaromontoro** [comment]
This is a great catch. I think it's because I set a min-width in the input. Let me double-check the code and I'll get a fix out. Thanks for reporting the issue.
