### ISSUE TITLE
CDN option

### ISSUE THREAD

**Issue by krcourville** [alvaromontoro/almond.css#53]
Hello,

In a blog post, I saw there was at least one other person asking about a CDN deployment option for almond.css.  I am not if there is a plan for publishing to npm, but an option, for those interested, is to use jsdelivr, which works for both github and npm.

Example stylesheet reference:

```html
<link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.jsdelivr.net/gh/alvaromontoro/almond.css@v1.0.0/dist/almond.min.css"
    />
```

[Example Stackblitz app](https://stackblitz.com/edit/web-platform-pqka5q?file=index.html)

Maybe this is useful for the README?

**Comment by alvaromontoro** [comment]
Thanks for the suggestion (and sorry for the late reply).

I added a reference to the jsDelivr file in the README (using mostly the text from this ticket 😳).

> ## CDN
>
>We are working on CDN/NPM publication options. In the meantime, an alternative for those interested, is to use [jsDelivr](https://www.jsdelivr.com/), which works for both github and npm.
>
>Example stylesheet reference (**You only need one, not both**):
>
```html
<!-- loads all the styles, including icons and images -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/alvaromontoro/almond.css@latest/dist/almond.min.css" />

<!-- loads a lighter version of the library: no icons or images -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/alvaromontoro/almond.css@latest/dist/almond.lite.min.css" />
```
>
> More CDN, NPM options coming up soon.

**Comment by alvaromontoro** [comment]
Almond.CSS is available now as an npm package.

Steps to include it (using `npm`):

1. Install the package:

        npm install almond.css

2. In the app entry point (e.g. in apps created with create-react-app, it would be App.js), add the import:

        import "almond.css/dist/almond.min.js";

3. Build and run your app
