### ISSUE TITLE
Second use of <blockquote> displays differently to first use

### ISSUE THREAD

**Issue by ColMcp** [alvaromontoro/almond.css#56]
The first `<blockquote>` in a document starts with a stylised opening double quote. The second use displays with a stylised opening _single_ quote.

I think this is because the `blockquote::before` block of `almond.css` uses `content: open-quote`. Since there is no following use of `close-quote` the next use of `open-quote` (in a following block quote) is assumed to be embedded in the first quote.

I changed the `blockquote::before` `content:` to be a literal open string quote character and two successive block quotes displayed the same (with a double open quote).

I don't know much about CSS so there may be a more appropriate way to fix this.

**Comment by alvaromontoro** [comment]
Thanks for reporting this (and sorry for the late reply). I'm running tests and looking into it.
Will have a fix soon.

**Comment by alvaromontoro** [comment]
You hit the nail with the analysis. I incorrectly assumed that the quote depth would be closed/reduced after the end of the block. Looking at the [CSS specification](https://w3c.github.io/csswg-drafts/css-content/#propdef-quotes), that is not the case. I added a `content: no-close-quote` in the `::after` to avoid this issue (I considered doing `content: open-quote no-close-quote` in the `::before` but I feared it could affect the descendants' style.

PR and fix coming up soon.

**Comment by alvaromontoro** [comment]
The issue should be fixed now. Thanks again for reporting.

<img width="695" alt="screenshot showing two blockquote styled with almond.css" src="https://user-images.githubusercontent.com/2205212/212238917-faec0163-66d6-47bd-bdcc-a8e6a6ace4c7.png">
