### ISSUE TITLE
`import "almond.css/dist/almond.min.js"`  doesn't work

### ISSUE THREAD

**Issue by yumafuu** [alvaromontoro/almond.css#90]
**Describe the bug**

I think the path for npm installation in the README is wrong.

I think the import ext is `css`.
The file that exists in dist is css

```bash
$ bun i almond.css
$ ls node_modules/almond.css/dist
almond.css  almond.lite.css  almond.lite.min.css  almond.min.css
```

So this worked.
```diff
- import "almond.css/dist/almond.min.js"
+ import "almond.css/dist/almond.min.css"
```

**Steps to reproduce**

**Expected behavior**

**Screenshots**

**Devices**
- macOS

**Additional context**

**Comment by alvaromontoro** [comment]
Good catch. This is a mistake in the README file.

If you are participating in Hacktoberfest, feel free to make the change, and I'll approve it. If not, I will push the change shortly.

Thanks for letting me know.

**Comment by yumafuu** [comment]
@alvaromontoro 

I made a PR https://github.com/alvaromontoro/almond.css/pull/91

Thank you for the opportunity to contribute!

**Comment by alvaromontoro** [comment]
@yumafuu Thank you for catching the issue and contributing!

I just merged the change.
